### ISSUE TITLE
Support for environments

### ISSUE THREAD

**Issue by aaronchi** [cjbottaro/app_config#1]
Would it be possible to add support for environments to app_config in a similar manner as settingslogic?

**Comment by cjbottaro** [comment]
I'm not sure what you mean.  It does support the notion of different configurations for different environments.  It even supports the idea of "inheritance".  Look at README.rdoc in the "inheritance" and "using in a Rails app" sections.

**Comment by aaronchi** [comment]
Instead of using different configs for each environment, it would be nice to be able to set the environments in the yml file like the database.yml file that rails uses.

Settingslogic supports this:
http://github.com/binarylogic/settingslogic/tree/master

# app/config/application.yml

  defaults: &defaults
    cool:
      saweet: nested settings
    neat_setting: 24
    awesome_setting: <%= "Did you know 5 + 5 = " + (5 + 5) + "?" %>

  development:
    <<: *defaults
    neat_setting: 800

  test:
    <<: *defaults

  production:
    <<: *defaults

**Comment by cjbottaro** [comment]
Ok, I added support for that in 1.1.0.  See the section "environments" in README.rdoc.  The gem should be built shortly on github.
