### ISSUE TITLE
Support for local override file

### ISSUE THREAD

**Issue by retr0h** [cjbottaro/app_config#2]
It would be nice if the file inheritance could be used in combination with the newly added single yaml file.

I would find it very useful to have a local override file always configured, and app_config not raise an error if it doesn't exist.  This allows me to have the local file git ignored, and make changes that I do not want checked in, yet I can always count on.

**Comment by cjbottaro** [comment]
I'm not quite sure what you mean.  Do you mean you want functionality that does something like this?
http://gist.github.com/179793

**Comment by retr0h** [comment]
Hey Christopher,

I have home written my own app config, which is very similar to yours now that you support the single yaml file.  However, I would rather not re-invent yet another app config, and would love to migrate to yours.

When I mean a local yaml file, I mean that file can override any arbitrary sections in the main yaml file.  Configuring app config would remain the same, yet, it wouldn't get pissed at me if the local override file was missing.

Here is an example:  http://gist.github.com/179886

It's nice to have the ability to change a default, for the currently selected env, and not have to worry about checking that in.  In my app config I also always merge the current env into defaults, vs having to merge them in via yaml.

**Comment by cjbottaro** [comment]
This feature is implemented in 1.2.0.  This gist explains how it works... http://gist.github.com/183094

I hope I understood you correctly and that gives you the functionality you want.

Note that the local override file _is_ recursively merged with environment of the first file.

**Comment by retr0h** [comment]
Somehow I can't find my reply.

Very cool.  This gist appears to do what I was hoping it would do.  I had one more question.

Is there a reason we do not recursive merge in the single yaml file, and is there a reason we do not merge onto a default if it exists by default?  Rather than having to 
add the <<: *merge in every section?

When doing <<: *merge that nils out keys.  It is nice to only specify what should change in the environment section of the yaml file.  It is then nice to override those with the _local file.

The way it currently works:

default: &default
  foo:
    bar:
      baz: value
      xyzzy: value 

development:
  <<: *default
  foo:
    bar:
      baz: new_value

Unfortunately with that merge xyzzy is undefined.   This kinda goes against what I would expect.  However, I do understand <<: merge does that.  Which is why it would be nice to always merge into a default section preserving the default's structure.

What do you think?  Did I explain it ok?
