### ISSUE TITLE
plugin wants RAILS_ENV.yml

### ISSUE THREAD

**Issue by masterkain** [cjbottaro/app_config#4]
hi,
I installed app_config as a plugin and I'm trying to keep environments configuration in one file.

as suggested in the readme, I proceeded to create a single config/app_config.yml to keep my stuff in.
following the docs I then put in an initializer:

::AppConfig = ApplicationConfiguration.new("app_config.yml")
AppConfig.use_environment!(RAILS_ENV)

script/console:

/edited/vendor/plugins/app_config/lib/app_config.rb:54:in `initialize':Errno::ENOENT: No such file or directory - /edited/config/environments/development.yml

**Comment by cjbottaro** [comment]
Ok, I see what's going on.  Since you installed it as a plugin (and not a gem), Rails is running the plugin's init.rb.  Simply comment out the contents or delete that file, then your initializer should work.

Please close the issue if that worked.
